# Generated by Django 4.2.3 on 2023-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_alter_carmodel_production_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='production_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
